#server:
#  port: 80
#  tomcat:
#    uri-encoding: utf-8
  

spring:
  banner:    charset: utf-8
  profiles:
    active:
    - localhost
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:./datafile/
  batch:    initialize-schema: always
    job:      names: itemReadJobemo
  jpa:
    database: MYSQL
    #open-in-view: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
        thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
    mode: HTML5